<?php

namespace chippyash\Test\Authentication\Manager\Exceptions;
use Chippyash\Authentication\Manager\Exceptions\AuthManagerException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-20 at 06:02:42.
 */
class AuthManagerExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AuthManagerException
     */
    protected $object;

    public function testExceptionExtendsBasePHPException() {
        $this->object = new AuthManagerException;
        $this->assertInstanceOf('Exception', $this->object);
    }
}
